"""empty message

Revision ID: ffa474b1f438
Revises: 6abad0a1059f
Create Date: 2024-07-15 17:32:17.906468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa474b1f438'
down_revision = '6abad0a1059f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taks_id', sa.Integer(), nullable=False),
    sa.Column('previous_assignee_id', sa.Integer(), nullable=False),
    sa.Column('new_assignee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['new_assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['previous_assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['taks_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taskhistory')
    # ### end Alembic commands ###
